module.exports = {
    name: 'topic',
    run: async (client, message, args) => {
        let replies = ["What is something you've never done but would like to try to do?",
        "What is something you've tried but would never do again?",
        "Are you a hoarder or saver?",
        "Are you usually early, late, or on time?",
        "What is your best skill/talent?",
        "What do you like least about living in your city/town?",
        "What do you like most about living in your city/town?",
        "Do you usually break the rules or follow them?",
        "Are you a leader or a follower?",
        "Do you wake up by yourself, to an alarm, music, or have someone else wake you up?",
        "Are you more of a spontaneous or structured person?",
        "How would your friends and family describe you?",
        "How have your goals changed as you've gotten older?",
        "Describe your dream house to me.",
        "What's the best thing to do on a hot summer day?",
        "What's the best thing to do on a cold winter day?",
        "What is your favorite smell?",
        "Do you prefer to receive money or an actual gift?",
        "What is your favorite day of the year?",
        "Are you messy or organised?",
        "Are you a heavy or a light sleeper?",
        "Do you smile for pictures?",
        "Do you wear slippers at home?",
        "Do you remember the last dream you had?",
        "How have you changed since you were a kid?",
        "Do you untie your sneakers before taking them off?",
        "After a long day, do you prefer to hang out with friends or spend time alone?",
        "What is your favorite brand?",
        "What do you like to do to celebrate your birthday?",
        "What is your favorite thing to do on a rainy day?",
        "What do you like to spend your money on?",
        "Do you prefer to relax in your free time or do something active?",
        "Do you shower in the morning or at night? Why?",
        "What is your favorite party/board game?",
        "Do you prefer to wear fashionable clothes or comfortable clothes?",
        "What is your favorite dessert?",
        "Do you prefer sweet or salty snacks?",
        "If someone you were trying to impress was coming over to your home for dinner, what would you make for them?",
        "What was your worst restaurant experience?",
        "What's your favorite non-alcoholic drink?",
        "How important is the decor of a restaurant to you?",
        "Do you prefer to travel or stay close to home?",
        "When going on a vacation, would you prefer to join a tour or plan out everything by yourself?",
        "What's your favorite thing about going on vacation?",
        "What's your least favorite thing about going on vacation?",
        "Have you ever gone on vacation by yourself?",
        "What do you like to do when you go to the beach?", "What three words best describe you?", "Do you have any pets? What are their names?",
        "Where did you go last weekend?", "What did you do last weekend?", " What did you do on your last vacation?", "What type of movies do you like to watch?",
        "Would you rather watch or play sports?",
        "What do you use to listen to music?",
        "Do you have a big family?",
        "What is the first thing that you notice about someone of the opposite gender?",
        "What do you look for in a girl/guy?",
        "What qualities do you value most in a friend?",
        "What is the first thing that you notice when meeting someone new?"]
        let result = replies[Math.floor(Math.random() * replies.length)];
        message.channel.send(result)
    }}